set(
    SRC
    src/utils/DynamicLibrary.cpp
    src/utils/Files.cpp
    src/utils/Observable.cpp
    src/utils/Scheduler.cpp
    src/utils/Stopwatch.cpp
    src/utils/Time.cpp
    src/utils/Worker.cpp
    src/sdl/InputMapper.cpp
    src/sdl/Sound.cpp
    src/sdl/Window.cpp
    src/net/HTTPClient.cpp
    src/net/UDP.cpp
)